# Homework #6

## Build a "dashboard" interface for the buildings dataset

### Left Component

In [1]:
import pandas as pd
import numpy as np
import bqplot
import traitlets
import ipywidgets
import matplotlib.pyplot as plt
%matplotlib inline

buildings = pd.read_csv('building_inventory.csv') # read dataset
buildings.dropna()
buildings # take a quick look at the dataset

,Agency Name,Location Name,Address,City,Zip code,County,Congress Dist,Congressional Full Name,Rep Dist,Rep Full Name,...,Bldg Status,Year Acquired,Year Constructed,Square Footage,Total Floors,Floors Above Grade,Floors Below Grade,Usage Description,Usage Description 2,Usage Description 3
0,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,1975,1975,144,1,1,0,Unusual,Unusual,Not provided
1,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,2004,2004,144,1,1,0,Unusual,Unusual,Not provided
2,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,2004,2004,144,1,1,0,Unusual,Unusual,Not provided
3,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,2004,2004,144,1,1,0,Unusual,Unusual,Not provided
4,Department of Natural Resources,Anderson Lake Conservation Area - Fulton County,Anderson Lake C.a.,Astoria,61501,Fulton,17,Cheri Bustos,93,Hammond Norine K.,...,In Use,2004,2004,144,1,1,0,Unusual,Unusual,Not provided
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8857,Department of Transportation,Belvidere Maintenance Storage Facility - Boone...,9797 Illinois Rte. 76,Belvidere,61008,Boone,16,Adam Kinzinger,69,Sosnowski Joe,...,In Use,0,0,432,1,0,0,Storage,NaN,NaN
8858,Department of Transportation,Belvidere Maintenance Storage Facility - Boone...,9797 Illinois Rte 76,Belvidere,61008,Boone,16,Adam Kinzinger,69,Sosnowski Joe,...,In Use,0,0,330,1,0,0,Storage,NaN,NaN
8859,Department of Transportation,Quincy Maintenance Storage Facility,800 Koch's Lane,Quincy,62305,Adams,18,Darin M. LaHood,94,Frese Randy E.,...,In Use,0,1987,130,1,0,0,Storage,High Hazard,NaN
8860,Illinois Community College Board,Illinois Valley Community College - Oglesby,815 North Orlando Smith Avenue,Oglesby,61348,LaSalle,16,Adam Kinzinger,76,Long Jerry Lee,...,In Use,1971,1971,49552,1,1,0,Education,Education,Not provided
8861,Department of Military Affairs,Peoria Army Aviation Support Facility,2323 S. Airport Rd,Peoria,61607,Peoria,17,Cheri Bustos,92,Gordon-Booth Jehan,...,In Progress,0,2017,288,1,0,0,Utiility & Miscellan,Utiility & Miscellan,NaN

In [2]:
# build left component
# 1. Data
# calculate the sum of total square footage for different criteria
totalSum = buildings.groupby(['Congress Dist', 'Agency Name'])['Square Footage'].sum().reset_index(name='Sum of total square footage')
df = pd.DataFrame(totalSum)
df.sort_values(by='Congress Dist')
df

,Congress Dist,Agency Name,Sum of total square footage
0,0,Department of Central Management Services,231278
1,0,Department of Human Services,372784
2,0,Department of Natural Resources,40249
3,0,Department of State Police,8239
4,0,Department of Transportation,55578
...,...,...,...
151,18,Department of Transportation,516516
152,18,Department of Veterans' Affairs,652160
153,18,Historic Preservation Agency,175427
154,18,Illinois Community College Board,252623
155,18,Western Illinois University,1962213

In [3]:
row_unique = df['Congress Dist'].unique()
col_unique = df['Agency Name'].unique()
data = pd.DataFrame(index = row_unique, columns = col_unique)
for i in df.index:
    data.loc[df['Congress Dist'][i],df['Agency Name'][i]] = df['Sum of total square footage'][i]
data = data.fillna(0)
data

,Department of Central Management Services,Department of Human Services,Department of Natural Resources,Department of State Police,Department of Transportation,Department of Veterans' Affairs,Historic Preservation Agency,Illinois Emergency Management Agency,Illinois Medical District Commission,Northern Illinois University,...,Southern Illinois University,Appellate Court / Fourth District,Department of Revenue,Governor's Office,Illinois Courts,Illinois State University,Eastern Illinois University,Appellate Court / Third District,Office of the Attorney General,Western Illinois University
0,231278,372784,40249,8239,55578,3000,3831,5650,31200,41315,...,0,0,0,0,0,0,0,0,0,0
1,0,449547,0,0,118143,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1253943,59050,0,287509,479061,287000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,14583,132581,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,34982,0,57800,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,9932,362890,0,0,112120,185525,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,24105,0,29996,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,2088840,304039,0,85708,54492,0,2364,0,15000,0,...,0,0,0,0,0,0,0,0,0,0
8,65268,913263,0,9776,398743,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,8228,0,69750,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,443865,234642,200392,6246,3270,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,66673,0,30914,73072,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,98355,1579965,649139,113685,638311,40000,123924,0,0,0,...,5558744,0,0,0,0,0,0,0,0,0
13,1003106,192934,571050,272619,1034012,0,795120,50000,0,0,...,3150729,16400,913236,45120,54540,2960272,0,0,0,0
14,0,0,173515,0,92420,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,70160,394598,574690,26710,838934,0,98011,0,0,0,...,0,0,0,0,0,0,1164674,0,0,0
16,44130,206088,577616,40242,738336,124235,11700,0,0,3709780,...,0,0,0,0,0,0,0,18700,0,0
17,151963,247839,402882,50974,430972,0,112777,0,0,0,...,0,0,0,0,0,0,0,0,60500,385896
18,54014,1887569,656403,169155,516516,652160,175427,0,0,0,...,0,0,0,0,0,0,0,0,0,1962213

In [4]:
# 2. Scales
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()
col_sc = bqplot.ColorScale(scheme="Blues")

# 3. Axis
ax_x = bqplot.Axis(scale = x_sc, label='Governmental department')
ax_y = bqplot.Axis(scale = y_sc, orientation='vertical', label='Congressional District')
ax_col = bqplot.ColorAxis(scale = col_sc, orientation='vertical', side='right')

# 4. Mark
heat_map = bqplot.GridHeatMap(color=np.array(data),
                            scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                            interactions={'click':'select'},
                            anchor_style={'fill':'pink'},
                            selected_style={'opacity':1.0},
                            unselected_style={'opacity':0.8})

# build the gridheatmap
fig = bqplot.Figure(marks = [heat_map], axes=[ax_col, ax_x, ax_y])

### Right Component

In [5]:
# 1. Data
groupYear = buildings.groupby(['Year Acquired'])['Square Footage'].sum().reset_index(name='Total Footage')

# 2. Scales
x_scl = bqplot.OrdinalScale()
y_scl = bqplot.LinearScale()

# 3. Axis
x_axl = bqplot.Axis(scale=x_scl, label='Year')
y_axl = bqplot.Axis(scale=y_scl, label='Total Square Footage Acquired that Year', orientation='vertical')

# 4. Marks
# set region mask
region_mask = (groupYear['Year Acquired']>=1900) & (groupYear['Year Acquired']<=2000)\
& (groupYear['Total Footage']>=10000) & (groupYear['Total Footage']<=400000)

linePlot = bqplot.Lines(x = groupYear['Year Acquired'][region_mask],\
                        y = groupYear['Total Footage'][region_mask],\
                        scales={'x':x_scl, 'y':y_scl}, line_style='solid')

# build the lineplot
figl = bqplot.Figure(marks = [linePlot], axes = [x_axl, y_axl])

### Link left and right components and display the dashboard

In [6]:
# 5. Interactions and Linking
mySelectedLabel = ipywidgets.Label() # a widget label
def on_selected(change):
    if len(change['owner'].selected) == 1:
        i, j = change['owner'].selected[0]
        print(i,j)
        v = data.iloc[i][j]
        mySelectedLabel.value = 'Sum of Total Square Footage = ' + str(v)
        # link to the line plot
        dfl = buildings[buildings['Congress Dist']==i]
        dfline = buildings[buildings['Agency Name']==col_unique[j]]
        groupYear = dfline.groupby(['Year Acquired'])['Square Footage'].sum().reset_index(name='Total Footage')
        # set region mask
        region_mask = (groupYear['Year Acquired']>=1900) & (groupYear['Year Acquired']<=2000)\
        & (groupYear['Total Footage']>=10000) & (groupYear['Total Footage']<=400000)
        print(groupYear.loc[region_mask])
        linePlot.x = groupYear['Year Acquired'][region_mask]
        linePlot.y = groupYear['Total Footage'][region_mask]

# link heatmap with the function
heat_map.observe(on_selected, 'selected')

# change line plot style
lineStyle = ['solid', 'dashed', 'dotted', 'dash_dotted']
lineStylePicker = ipywidgets.Dropdown(options=lineStyle, value=lineStyle[0], disabled=False)
ipywidgets.link((lineStylePicker,'value'),(linePlot,'line_style'))

# create the linked dashboard
fig.layout.min_width='700px'
figl.layout.min_width='700px'
figures = ipywidgets.HBox([fig,figl])
picker = ipywidgets.VBox([mySelectedLabel,lineStylePicker])
myDashboard = ipywidgets.VBox([picker, figures])
myDashboard

VBox(children=(VBox(children=(Label(value=''), Dropdown(options=('solid', 'dashed', 'dotted', 'dash_dotted'), …

13 11
    Year Acquired  Total Footage
2            1922          52500
3            1931         299772
4            1938         367138
5            1939          25613
6            1940         272959
7            1942          64581
8            1949          43472
9            1950         236953
10           1951          43639
11           1952          45539
12           1953          64238
13           1954          68406
14           1956          63683
15           1957          18750
16           1958          87866
17           1959          20379
19           1965          48525
21           1972          12411
24           1976          88687
25           1977          20745
26           1978         144931
29           1981         216283
33           1985          65642
34           1986         125865
35           1987          33626
37           1989         184886
38           1990         188190
39           1991         120747
40           1992          49553
42           1995          64005
45           2000         129713
14 10
   Year Acquired  Total Footage
2           1970         183964
3           1971          70995
4           1972          49841
6           1979          70995

## Write-up

### Collaboration

For this homework, I worked with two classmates to solve some problems we met together, Xinze Fan and Augustine Xu. We discussed the problems we met during doing this homework, such as, what data transformations we need to do in order to plot the GridHeatMap with categorical columns (Congress district and Agency Name). So, we worked together to create a 2d matrix to store the sum of total square footage as weighted, and plot this 2d array into the GridHeatMap. And we built the line plot and the linkage together too. I believe that each of us contribute equally to solve the problems we met during doing this homework.

### Any data transformations or rescalings you did for your plot

Since the row and the column of the GridHeatMap we need to made are categorical data, and the color of the heatmap should be the sum of total square footage as weight, I firstly create a new dataframe to store these three columns I need. By grouping by the sorted congress district and the agency name, I got a list of values that are the sum of total square footage for the corresponding criteria. Then, I built a 2d matrix to store the total footage, where the indexes are the unique congress district and the columns are all the governmental department name. Therefore, this 2d array can fit to the GridHeatMap to make a plot like above.

### How you dealt with NaN's (empty entries) in your dataset

Since there are lots of empty space in the 19 by 35 matrix, I used .fillna() function to replace all the NaN values with 0, so that they can successfully be plotted into the GridHeatMap. These NaN values represent that the conbination of the congress district and the governmental department does not exist, so there will not be any square footage in that area. Therefore, I replace these NaN values with zero.

### Any aesthetic choices you made (colors, layout, plot size, label size) and why, and what you'd like to experiment with if you had more time.

For the GridHeatMap, I set the color scale to be blue, and the color of being selected to be pink. I think it is very obvious and beautiful. As we did in class, I also set the opacity for the selected cell to be 1.0, and the unselected cell to be 0.8. For the line plot, I only set the line style to be solid as default. After linking and plotting them together, it is too small for the line plot to show all its x labels, so I change the plot size to 800 pixels. I believe that I successully keep the x and y ranges to be static by using a region mask. I set the region of the acquired year between 1900 and 2000 and the total square footage between 10000 and 400000. By doing this, the data being plotted are in this range, and the axes ranges are more stable than before. Also, I created a Dropdown widget to allow users to change the style of the line in the line plot. 

If I had more time, I would like to try to build ipywidgets that can change the fields being plotted in the line plot, and maybe widgets that can change the marks we used to plot not only GridHeatMap. I also want to play around more interesting layout attributes to change some properties in the plots.

# End of Homework 6